name: Tests

on:
  workflow_dispatch:
  schedule:
   - cron: '0 */6 * * *'
    
permissions:
  contents: read
  
env:
  MONGO_URI : ${{secrets.MONGO_URI}}

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '20'


    - name: Setup CF
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb && sudo cloudflared service install ${{ secrets.CF_KEY }}


    - name: Install Dependencies
      run: npm install pm2 vite -g && npm install
      working-directory: ./

    - name: Setup Deploy
      run: |
        NODE_ENV=production
        vite build
      # pm2 start server/app.js -i 4
        cd server && node app.js

      working-directory: ./ 

 